//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int Id { get; set; }
        public string TokenData { get; set; }
        public string Device { get; set; }
        public string Platfrom { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> ExpiredAt { get; set; }
        public string GMT { get; set; }
        public string OS { get; set; }
        public Nullable<int> LoginId { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
