//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequest
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string RequestTitle { get; set; }
        public string RequestCategorie { get; set; }
        public string ImdbLink { get; set; }
    
        public virtual User User { get; set; }
    }
}
