//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Expanses = new HashSet<Expans>();
            this.Packages = new HashSet<Package>();
            this.Salarys = new HashSet<Salary>();
            this.Videos = new HashSet<Video>();
            this.Auths = new HashSet<Auth>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Role { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AccountCreateTime { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    
        public virtual ICollection<Expans> Expanses { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
        public virtual ICollection<Salary> Salarys { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual ICollection<Auth> Auths { get; set; }
    }
}
